services:
  postgres:
    image: postgres:17.5-alpine
    command: postgres -c 'max_connections=200'
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: puzzl_games

volumes:
  postgres-data: