spring.application.name=puzzl-games

spring.datasource.url=jdbc:postgresql://localhost:5432/puzzl_games
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

server.port=8080

spring.thymeleaf.cache=false
